site_name: "ECT2 Informatique - Lycée Nicolas Brémontier -  Bordeaux"

site_url: https://glassus.github.io/ect2

theme:
  name: material
  custom_dir: my_theme_customizations/
  font: false
  language: fr
  icon:
    logo: material/code-greater-than
    repo : fontawesome/brands/github
  favicon: xtra/fav.png

  features:
    - navigation.instant
    - navigation.tabs
    - navigation.expand
    #- navigation.top
    - toc.integrate
    - header.autohide
    - content.code.annotate 
    - content.code.copy

  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/toggle-switch-off-outline
        name: Mode sombre

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/toggle-switch
        name: Mode clair


markdown_extensions:
  - meta
  - abbr
  - admonition
  - def_list
  - attr_list
  - footnotes
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.highlight:
      linenums: None
  - pymdownx.tasklist:
      custom_checkbox: false
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: ⚓︎
      toc_depth: 3


plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: false
      locale: fr
  - awesome-pages:
      collapse_single_pages: false
  - sqlite-console
  - macros
 
 # - mkdocs-jupyter

extra:
  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:gilles.lassus@ac-bordeaux.fr
      name: Écrire à l'auteur


extra_javascript:
  - scripts/mathjax.js
  - xtra/javascripts/interpreter.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/highlight.min.js



extra_css:
  - stylesheets/extra.css
  - xtra/stylesheets/pyoditeur.css
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css


copyright:  CC BY-SA / G.Lassus
